### ISSUE TITLE
Issue de testeo (obsoleto)

### ISSUE THREAD

**Issue by JuanCruzMz** [PedroS2001/TP_SO_i1_Equipo5#1]
Hola
?

**Comment by PedroS2001** [comment]
te llega notificacion si respondo?

**Comment by JuanCruzMz** [comment]
Si, al mail. Excelente!

**Comment by JuanCruzMz** [comment]
Holaa. Estamos todos?

**Comment by PedroS2001** [comment]
Holaa, creo que si

**Comment by JuanCruzMz** [comment]
Ya estaria mi primera parte

**Comment by JuanCruzMz** [comment]
Che, mejor hablemos por el issue del repositorio de Martinez, que ahi esta el

**Comment by PedroS2001** [comment]
sisi es mejor ahi
